[package]
name = "rnix"
version = "0.1.0"
authors = ["Jude Taylor <me@jude.xyz>"]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
parking_lot = "0.11.0"
arena = { path = "arena" }
syntax = { path = "syntax" }
codespan-reporting = "0.9.5"
codespan = "0.9.5"
async-std = { version = "1.6.2", features = ["attributes"] }
im = "15.0.0"
thiserror = "1.0.20"
termcolor = "1.1.0"
path_abs = "0.5.0"
log = "0.4.11"
serde_json = "1.0.56"
backtrace = "0.3.50"
rustyline = "6.2.0"
futures = "0.3.5"
async-recursion = "0.3.1"
pretty_env_logger = "0.4.0"
dirs-next = "1.0.1"
derive_more = "0.99.9"
binascii = "0.1.4"
lazy_static = "1.4.0"

[dev-dependencies]
tempfile = "3.1.0"
tar = "0.4.29"
reqwest = "0.10"
xz2 = "0.1.6"
proptest = "0.10.0"
assert_matches = "1.3.0"
hex = "0.4.2"

[workspace]
members = ["arena", "syntax"]

[features]
blackhole = []
default = []
