[package]
name = "rnix"
version = "0.1.0"
authors = ["Jude Taylor <me@jude.xyz>"]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
futures = "0.3.5"
parking_lot = "0.11.0"
arena = { path = "arena" }
syntax = { path = "syntax" }
codespan-reporting = "0.9.5"
codespan = "0.9.5"
async-std = "1.6.2"
async-recursion = "0.3.1"
im = "15.0.0"
thiserror = "1.0.20"
termcolor = "1.1.0"
path_abs = "0.5.0"
log = "0.4.11"
serde_json = "1.0.56"
backtrace = "0.3.50"

[dev-dependencies]
pretty_env_logger = "0.4.0"
tokio = { version = "0.2.21", features = ["macros", "rt-core", "parking_lot"] }
tempfile = "3.1.0"
tar = "0.4.29"
reqwest = { version = "0.10.6", features = ["blocking"] }
xz2 = "0.1.6"

[workspace]
members = ["arena", "syntax"]
