[package]
name = "rnix"
version = "0.1.0"
authors = ["Jude Taylor <me@jude.xyz>"]
edition = "2018"

# [workspace]
# members = [
#   "arena",
#   "core",
#   "eval",
#   "repl",
#   "store",
#   "syntax",
#   "util",
# ]

[dependencies]
parking_lot = "0.11.0"
lalrpop-util = "0.19.0"
codespan = "0.9.5"
derive_more = "0.99.9"
lazy_static = "1.4.0"
regex = "1.3.9"
string_cache = "0.8.0"
thiserror = "1.0.20"
log = "0.4.11"
codespan-reporting = "0.9.5"
itertools = "0.9.0"
im = "15.0.0"
anyhow = "1.0.32"
once_cell = "1.4.0"
rust-crypto = "0.2.36"
binascii = "0.1.4"
unix = { package = "nix", version = "0.17.0" }
rand = "0.7.3"
termcolor = "1.1.0"
path_abs = "0.5.0"
serde_json = "1.0.57"
pretty_env_logger = "0.4.0"
rustyline = "6.2.0"
dirs-next = "1.0.1"

[build-dependencies]
lalrpop = "0.19.0"

[dev-dependencies]
assert_matches = "1.3.0"
proptest = "0.10.0"
hex = "0.4.2"
