[package]
name = "rnix"
version = "0.1.0"
authors = ["Jude Taylor <me@jude.xyz>"]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
futures = "0.3.5"
parking_lot = "0.11.0"
typed-arena = "2.0.1"
arena = { path = "arena" }
syntax = { path = "syntax" }
codespan-reporting = "0.9.5"
codespan = "0.9.5"
async-std = "1.6.2"
async-recursion = "0.3.1"
im = "15.0.0"

[dev-dependencies]
tokio = { version = "0.2.21", features = ["macros", "rt-core", "parking_lot"] }
codespan-reporting = "0.9.5"
termcolor = "1.1.0"
anyhow = "1.0.31"
pretty_env_logger = "0.4.0"

[workspace]
members = ["arena", "syntax"]
