[package]
name = "rnix"
version = "0.1.0"
authors = ["Jude Taylor <me@jude.xyz>"]
edition = "2018"

[dependencies]
eval = { path = "eval" }
syntax = { path = "syntax" }

[workspace]
members = ["arena", "eval", "syntax"]

[dev-dependencies]
tokio = { version = "0.2.21", features = ["macros"] }
codespan-reporting = "0.9.5"
termcolor = "1.1.0"
anyhow = "1.0.31"
