[package]
name = "rix-eval"
version = "0.1.0"
authors = ["Jude Taylor <me@jude.xyz>"]
edition = "2018"

[dependencies]
parking_lot = "0.11.1"
rix-syntax = { path = "../syntax" }
rix-util = { path = "../util" }
