[package]
name = "rix-eval"
version = "0.1.0"
authors = ["Jude Taylor <me@jude.xyz>"]
edition = "2018"

[dependencies]
codespan-reporting = "0.9.0"
crossbeam = "0.8.0"
derivative = "2.1.1"
enum-as-inner = "0.3.3"
lazy_static = "1.4.0"
parking_lot = "0.11.1"
regex = "1.4.2"
rix-fetch = { path = "../fetch" }
rix-store = { path = "../store" }
rix-syntax = { path = "../syntax" }
rix-util = { path = "../util" }
serde = "1.0.118"
serde_json = "1.0.60"
slog-scope = "4.3.0"
smallvec = "1.5.1"
thiserror = "1.0.22"
