[package]
name = "rix-util"
version = "0.1.0"
authors = ["Jude Taylor <me@jude.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.35"
codespan = "0.11.0"
codespan-reporting = "0.11.0"
lazy_static = "1.4.0"
parking_lot = "0.11.1"
thiserror = "1.0.22"
