[package]
name = "nix-util"
version = "0.1.0"
authors = ["Jude Taylor <me@jude.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix-syntax = { path = "../syntax" }
anyhow = "1.0.31"
